name: GaunCraft_Resourcepack-2
version: '${project.version}'
main: com.gauncraft.pack.GaunCraftPack
api-version: '1.21'
description: Bliss resource pack'ini oyuncular girince otomatik gonderir
commands:
  gcbliss:
    description: Bliss pack komutu
    usage: /gcbliss <reload|send [oyuncu]>
    permission: gauncraftpack.admin
permissions:
  gauncraftpack.admin:
    description: Pack komutlarini kullanma
    default: op
    
